version: "3.9"
services:
  catalogservice:
    depends_on:
      - catalogsql
    image: catalogservice
    restart: on-failure
    build:
      context: ./Catalog
      dockerfile: catalogService
    ports:
      - "8081:8080"
    links:
      - "catalogsql:catalogsql"
    networks:
      - main
  catalogsql:
    build:
      context: ./Catalog
      dockerfile: CatalogSQL
    networks:
      - main


networks:
  main:
