version: "3.9"
services:
  catalog:
    depends_on:
      - catalogsql
    image: catalogservice
    restart: on-failure
    build:
      dockerfile: ./Dockerfile1
    ports:
      - "8080:8080"
    links:
      - "catalogsql:catalogsql"
    networks:
      - main
  catalogsql:
    image: catalogsql
    build:
      dockerfile: Dockerfile
    networks:
      - main
networks:
  main:
