spring:
  cloud:
    gateway:
      routes:
        - id: frontend_to_catalog_listing_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/listings/

        - id: frontend_to_catalog_listing_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/listings/

        - id: frontend_to_catalog_listing_get_route
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/listing/**

        - id: create_account_post
          uri: http://localhost:8082
          predicates:
            - Path=/accounts/

        - id: new_bid_post
          uri: http://localhost:8083
          predicates:
            - Path=/bid/newbid