name: Build and Test Services

on:
  push:
    branches:
      - main

jobs:
  build-services:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and install auction-common
        run: mvn clean install --file auction-common/pom.xml

      - name: Build and test Catalog Service
        run: mvn clean install --file Catalog/pom.xml

      - name: Build and test Account Service
        run: mvn clean install --file Account/pom.xml

      - name: Build and test Bidding Service
        run: mvn clean install --file Biddingservice/pom.xml
        
  publish-docker-images:
      name: Publish Docker Images
      runs-on: ubuntu-latest
      needs: build-services

      steps:
        - name: Checkout repository
          uses: actions/checkout@v2

        - name: Log in to Docker Hub
          uses: docker/login-action@v1
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}

        - name: Build and Push Docker Image for Catalog Service
          run: |
            docker build -t baumann21/catalog-service:latest Catalog/catalogService -f Catalog/catalogService
            docker push baumann21/catalog-service:latest

        - name: Build and Push Docker Image for Account Service
          run: |
            docker build -t baumann21/account-service:latest Account/Account-Docker -f Account/Account-Docker
            docker push baumann21/account-service:latest

        - name: Build and Push Docker Image for Bidding Service
          run: |
            docker build -t baumann21/bidding-service:latest Biddingservice/BiddingService -f Biddingservice/BiddingService
            docker push baumann21/bidding-service:latest
