name: Java CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build auction-common
        run: |
          cd auction-common
          mvn clean install -DskipTests
          cp target/auction-common.jar ../

      - name: Build Biddingservice
        run: |
          cd Biddingservice
          mvn clean install -DskipTests
