name: Java CI

on:
  push:
    branches:
      - main

jobs:
  auction-common:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Build auction-common JAR
        run: mvn clean install -DskipTests

      - name: Upload auction-common artifact
        uses: actions/upload-artifact@v2
        with:
          name: auction-common
          path: target/auction-common.jar

  Biddingservice:
    needs: auction-common
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt

      - name: Download auction-common artifact
        uses: actions/download-artifact@v2
        with:
          name: auction-common
          path: target

      - name: Build Biddingservice
        run: mvn clean install -DskipTests
