name: Build and Test Services

on:
  push:
    branches:
      - main

jobs:
  build-services:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Cache Maven dependencies
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven-

      - name: Build and test auction-common
        run: mvn clean install --file auction-common/pom.xml

      - name: Build and test Catalog Service
        run: mvn clean install --file Catalog/pom.xml

      - name: Build and test Bidding Service
        run: mvn clean install --file Biddingservice/pom.xml

      - name: Build and test Account Service
        run: mvn clean install --file Account/pom.xml
