name: Build and Test Services

on:
  push:
    branches:
      - main

jobs:
  build-services:
    name: Build and Test Services
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Build Auction Common
        run: mvn clean install --file auction-common/pom.xml

      - name: Install Auction Common in Local Repository
        run: mvn install:install-file -Dfile=auction-common/target/auction-common-0.0.1-SNAPSHOT.jar -DgroupId=sdu.se06 -DartifactId=auction-common -Dversion=0.0.1-SNAPSHOT -Dpackaging=jar

      - name: Build and test Bidding Service
        run: mvn clean install --file Biddingservice/pom.xml

      - name: Build and test Catalog Service
        run: mvn clean install --file Catalog/pom.xml

      - name: Build and test Account Service
        run: mvn clean install --file Account/pom.xml
